# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: test
    silent: true

  test:
    desc: Run tests
    cmds:
      - go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - go tool cover -func coverage.out