name: Release

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.16.x]
        include:
          - os: macos-latest
            artifact: pod-macOS
            path: pod.zip
            cmd: |
              wails build -p
              npm install -g appdmg
              appdmg dmg-spec.json pod.dmg
              zip pod.zip pod.dmg

          - os: ubuntu-18.04
            artifact: pod-linux
            path: pod.tar.gz
            cmd: |
              sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
              wails build
              tar -czvf pod.tar.gz ./build/pod
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Version
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get Wails
        run: go get -u github.com/wailsapp/wails/cmd/wails

      - name: Build package
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          echo "building on ${{ matrix.os }}"
          mkdir -p ~/.wails
          cp wails.json ~/.wails/
          export LOG_LEVEL=debug
          export GODEBUG=1
          ${{ matrix.cmd }}

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.path }}
          retention-days: 5

  release:
    runs-on: ubuntu-18.04
    needs: package
    steps:
      - uses: go-semantic-release/action@v1
        id: create_release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: true
          changelog-generator-opt: "emojis=true"
          allow-initial-development-versions: true

      - name: Download macOS package
        uses: actions/download-artifact@v2
        with:
          name: pod-macOS

      - name: List downloaded OSX files
        run: |
          ls -R

      - name: Upload macOS package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{steps.create_release.outputs.version}}
          file: ./pod.zip
          asset_name: pod_${{steps.create_release.outputs.version}}_macOS.zip

      - name: Download linux package
        uses: actions/download-artifact@v2
        with:
          name: pod-linux

      - name: List downloaded Linux files
        run: |
          ls -R

      - name: Upload Linux package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{steps.create_release.outputs.version}}
          file: ./pod.tar.gz
          asset_name: pod_${{steps.create_release.outputs.version}}_linux_x86_64.tar.gz
