name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: go-semantic-release/action@v1
        id: create_release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: true
          changelog-generator-opt: "emojis=true"
          allow-initial-development-versions: true
