name: Test

on: [pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Wails dependencies
        run: sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev gir1.2-appindicator3-0.1

      - name: Setup wails
        run: go get -u github.com/wailsapp/wails/cmd/wails

      - name: Build deps
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go env

          mkdir -p ~/.wails
          cp wails.json ~/.wails/
          export LOG_LEVEL=debug
          export GODEBUG=1
          export LOG_LEVEL=debug
          export GODEBUG=1

      - name: Test backend
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out ./...
          go tool cover -func coverage.out
