name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Test frontend
      working-directory: frontend
      run:
        npm install
        npm run test:unit

    - name: Test backend
      run: |
        go test -race -covermode=atomic -coverprofile=coverage.out ./...
        go tool cover -func coverage.out