name: Test

on: [pull_request]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Test frontend
        working-directory: frontend
        run: |
          npm install
          npm run test:unit

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Wails dependencies
        run: sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Setup wails
        run: go get -u github.com/wailsapp/wails/cmd/wails

      - name: Build deps
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          mkdir -p ~/.wails
          cp wails.json ~/.wails/
          export LOG_LEVEL=debug
          export GODEBUG=1
          export LOG_LEVEL=debug
          export GODEBUG=1

      - name: Test backend
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out ./...
          go tool cover -func coverage.out
